In [109]:
### Numpy-> play with arrays(numbers)
### pandas->dataset
### matplotlib->Data Visualization
### seabparn->Data visualization
### Scipy->Statical
### Sklearn->Algorithm

## Numpy:Package for Multidimensional array

In [110]:
import numpy as np

In [111]:
list=[3,5,6]
np.array(list)

array([3, 5, 6])

In [112]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [113]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [115]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [116]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [117]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [118]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [121]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [122]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [123]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [124]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [125]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [126]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [127]:
np.random.rand(3,5)

array([[0.87227789, 0.55293844, 0.0289902 , 0.84150409, 0.72746766],
       [0.83153505, 0.44871511, 0.24688872, 0.43001244, 0.87986796],
       [0.03195642, 0.90721051, 0.25219137, 0.76480775, 0.41713557]])

In [128]:
arr=np.random.randn(2,4)
arr

array([[-0.03014062,  1.64892163,  1.55976782, -0.08394559],
       [-1.86375136,  0.38412304, -0.72773841, -0.13553126]])

In [129]:
np.random.randint(2,100)

54

In [130]:
np.random.randint(20,56,100,)

array([22, 46, 28, 30, 43, 40, 50, 49, 33, 41, 41, 51, 36, 34, 32, 53, 36,
       22, 55, 34, 47, 46, 34, 26, 34, 24, 48, 46, 39, 47, 35, 28, 43, 43,
       21, 23, 23, 22, 23, 44, 50, 46, 49, 33, 28, 22, 46, 49, 27, 22, 50,
       34, 28, 43, 41, 43, 45, 29, 24, 27, 54, 29, 25, 40, 31, 23, 37, 36,
       25, 37, 20, 28, 35, 46, 33, 33, 39, 40, 22, 38, 51, 25, 55, 24, 43,
       33, 42, 26, 51, 39, 36, 26, 29, 22, 42, 34, 30, 52, 36, 51])

In [131]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [132]:
rand_array=np.random.randint(0,10,50)
rand_array

array([5, 7, 0, 5, 3, 5, 4, 2, 9, 9, 5, 3, 0, 7, 2, 8, 5, 4, 0, 9, 4, 0,
       3, 4, 1, 9, 7, 3, 3, 1, 1, 9, 5, 1, 3, 6, 7, 5, 0, 6, 7, 2, 7, 3,
       6, 1, 5, 5, 3, 2])

In [133]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [135]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [136]:
rand_array.max()

9

In [137]:
rand_array.argmax()

8

In [138]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [139]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [140]:
a=np.random.rand(2,3)
a

array([[0.32032775, 0.86533255, 0.23921759],
       [0.08394254, 0.73674578, 0.27398314]])

In [141]:
a.T

array([[0.32032775, 0.08394254],
       [0.86533255, 0.73674578],
       [0.23921759, 0.27398314]])

In [142]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [143]:
sample_array[0]

10

In [144]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [145]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [146]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [147]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [148]:
subset_sample_array[:]=10001
subset_sample_array

array([10001, 10001, 10001, 10001, 10001, 10001, 10001])

### Two Dimensional array

In [149]:
import numpy as np

In [150]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[58,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [58, 76, 24,  7]])

In [151]:
sample_matrix[1,2]

21

In [152]:
sample_matrix[2,:]

array([58, 76, 24,  7])

In [153]:
sample_matrix[2]

array([58, 76, 24,  7])

In [154]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

### Selection Techniques

In [155]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [156]:
sample_matrix+sample_matrix

array([[100,  40,   2,  46],
       [ 48,  46,  42,  66],
       [116, 152,  48,  14]])

In [157]:
np.exp(sample_matrix)

array([[5.18470553e+21, 4.85165195e+08, 2.71828183e+00, 9.74480345e+09],
       [2.64891221e+10, 9.74480345e+09, 1.31881573e+09, 2.14643580e+14],
       [1.54553894e+25, 1.01480039e+33, 2.64891221e+10, 1.09663316e+03]])

In [158]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [159]:
np.log(sample_matrix)

array([[3.91202301, 2.99573227, 0.        , 3.13549422],
       [3.17805383, 3.13549422, 3.04452244, 3.49650756],
       [4.06044301, 4.33073334, 3.17805383, 1.94591015]])

In [160]:
np.max(sample_array)

19

In [161]:
np.min(sample_matrix)

1

In [162]:
np.argmin(sample_matrix)

2

In [163]:
np.argmax(sample_matrix)

9

In [164]:
np.square(sample_matrix)

array([[2500,  400,    1,  529],
       [ 576,  529,  441, 1089],
       [3364, 5776,  576,   49]])

In [165]:
np.std(sample_matrix)

20.473560185435915

In [166]:
np.var(sample_matrix)

419.1666666666667

In [167]:
np.mean(sample_matrix)

30.0

In [168]:
array=np.random.randn(3,4)
array

array([[ 1.63808886, -0.48395187, -1.61558282,  0.47983587],
       [ 1.06581352,  0.59579596,  1.31169092, -1.22599899],
       [ 0.48134299,  0.29548057, -2.42069782,  0.8048094 ]])

In [169]:
np.round(array,decimals=2)

array([[ 1.64, -0.48, -1.62,  0.48],
       [ 1.07,  0.6 ,  1.31, -1.23],
       [ 0.48,  0.3 , -2.42,  0.8 ]])

In [170]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### Pandas

In [171]:
import pandas as pd
import numpy as np

### Pandas dataframe and indexing

In [172]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [173]:
sports1['football']

2

In [174]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [175]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [176]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.259030  0.560405  0.528021  0.003765  0.460146
B  0.529267  0.455038  0.363950  0.386566  0.660895
C  0.977901  0.786645  0.412349  0.875680  0.340638
D  0.155369  0.877003  0.556805  0.900041  0.560332
E  0.450365  0.590682  0.888108  0.233741  0.777530
F  0.400315  0.848292  0.739833  0.492898  0.151860
G  0.745464  0.695644  0.221322  0.959293  0.943527
H  0.201056  0.187931  0.223270  0.122151  0.261010

In [177]:
df1["score1"]

A    0.259030
B    0.529267
C    0.977901
D    0.155369
E    0.450365
F    0.400315
G    0.745464
H    0.201056
Name: score1, dtype: float64

In [178]:
df1['score6']=df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.259030  0.560405  0.528021  0.003765  0.460146  0.819435
B  0.529267  0.455038  0.363950  0.386566  0.660895  0.984305
C  0.977901  0.786645  0.412349  0.875680  0.340638  1.764546
D  0.155369  0.877003  0.556805  0.900041  0.560332  1.032373
E  0.450365  0.590682  0.888108  0.233741  0.777530  1.041047
F  0.400315  0.848292  0.739833  0.492898  0.151860  1.248607
G  0.745464  0.695644  0.221322  0.959293  0.943527  1.441107
H  0.201056  0.187931  0.223270  0.122151  0.261010  0.388987

In [179]:
df2={'ID':['101','102','103','104','105'],'Name':['John','Mercy','sonal','piyu','rani'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  sonal      56
3  104   piyu      87
4  105   rani     123

In [180]:
df["ID"]

0    101
1    102
2    103
3    104
4    105
Name: ID, dtype: object

In [181]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  sonal
3  104   piyu
4  105   rani

In [182]:
df=df.drop("ID",axis=1)
df


Name  Profit
0   John      20
1  Mercy      54
2  sonal      56
3   piyu      87
4   rani     123

In [183]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  sonal      56
4   rani     123

Name  Profit
0   John      20
1  Mercy      54
2  sonal      56
3   piyu      87
4   rani     123